### PR TITLE
Gis comm mtg notes 20170418

### PR DESCRIPTION
**Pull request by geochik**
Please review notes and correct as necessary. Links to presentations and agency logos will be fixed shortly.

### CODE REVIEW

**Comment by ThorTheDestroyer** [comment]
Lidar portion looks correct.

**Comment by christoball** [comment]
- [ ] First Draft
- [ ] Add images, formatting edits @christoball
- [ ] Review built dev version
- [ ] Merge Pull Request and Publish

**Comment by christoball** [comment]
Built site version of draft seen here. Please review for final edits. @geochik @gmullins 

https://beta.tnris.org/geographic-information-office/2017-04-27/gis-community-meeting-recap-2nd-quarter/

**Comment by gmullins** [comment]
Links in the TxDOT section are not live. Everything else looks fine to me.

**Pull request merged**
