### PR TITLE
Fix favicon path

### PR DESCRIPTION
**Pull request by jseppi**

### CODE REVIEW

**Comment by jseppi** [comment]
@wilsaj should this use the `link` macro?

**Comment by wilsaj** [comment]
yeah, `link` macro would be better

**Comment by jseppi** [comment]
Ok, I think we'll have to modify the build a little bit better then. It was giving me errors when I tried to use it. Perhaps the order in which the favicon gets copied to dist and when the macro is executed is no bueno.

**Comment by wilsaj** [comment]
Oh right. Actually, the `based` macro is the one to use. Try: `{{m.based('favicon.ico')}}`

**Comment by wilsaj** [comment]
Difference is `link` tries to validate.

**Pull request merged**
