### PR TITLE
Update texas-google-imagery.md

### PR DESCRIPTION
**Pull request by geochik**
@gmullins 
@KCMack 

Please review changes and comment/edit as necessary. It's late in the day on Friday and my squirrel brain is tired.

### CODE REVIEW

**Comment by christoball** [comment]
About to merge this in, but wondering if we could get a screenshot of the 'new layers section'?

**Comment by christoball** [comment]
@geochik @gmullins @KCMack you can preview the changes in context at this link:
https://deploy.tnris.org/api/v1/preview/b34ac9405a7df1b8eab302d5859d9c04f71c43d4/texas-google-imagery/

**Comment by KCMack** [comment]
Minor change requested.

Many of us use Google imagery in our daily lives, whether looking up directions or exploring our neighborhood from **above.  Unique to** this innovative project, the State of Texas has collaborated with Google to harness this resource and provide a cost-efficient and widely accessible mapping tool that meets the needs of government agencies.

@christoball  will make the change.

**Comment by gmullins** [comment]
Finished my edits.
@christoball We will need individual Technical FAQ links under that section for the new FAQs: The Google Imagery Service now contains layers by year. What are these new layers? / Should I use the WMS service link or the WMTS service link? / The WMTS link does not work in ArcGIS Online. Can this be fixed?

**Comment by christoball** [comment]
@gmullins I'm not sure what you mean. In the order of the page, the questions are currently under the **General FAQ**.

It seems like the questions are sorted strongly between **general faq** and **technical faq**. Can y'all review them and see if we can clarify these categories? @geochik

**Pull request merged**
