### PR TITLE
GIO page revisions

### PR DESCRIPTION
**Pull request by Ldsmiths**
- Created cards for GIO events to help separate from page content 
- Removed arrows from GIS Solutions Group - Participating Agencies
- Updated 3 banners to matching sizes (Events, GIO: Main & GIS Soultions Group)
- Group Charter hyperlink text —> button & open in new tab
- Minor spacing changes with added br tags

### CODE REVIEW

**Comment by jwhaney** [comment]
holy css batman! this looks really great. well done. only comment i have is i'd suggest you make all the gio event cards the same height like we did on the stratmap contracts page with the built-in bootstrap classes.

**Review by jwhaney — CHANGES_REQUESTED** [review]
add bootstrap class like stratmap contracts page to make gio event cards uniform height.

**Comment by Ldsmiths** [comment]
This should make it so all cards match the height of the biggest. Spacing starts to look a little weird if one card has significantly more content, but as long as the descriptions are kept a relatively similar length it shouldn't be an issue. Only seems to be really noticeable if the description of a card is twice as long as another.

**Review by jwhaney — APPROVED** [review]
looks good

**Pull request merged**
