### PR TITLE
change field name to 'Name'

### PR DESCRIPTION
**Pull request by jseppi**

### CODE REVIEW

**Comment by jseppi** [comment]
Does that mean it worked?

**Comment by mitchellryant** [comment]
yes, it pulled the first name into the client

**Comment by KCMack** [comment]
The person to whom these job descriptions should be assigned is Erik O’Brian.

Kathleen C. Mack, PMP
Operations Manager
Texas Natural Resources Information System / 1700 N. Congress Ave., Austin, Texas 78701
Phone 512 463-4536 / Cell 512 415-3847
Kathleen.Mack@twdb.texas.gov<mailto:Kathleen.Mack@twdb.texas.gov> / www.tnris.texas.gov<http://www.tnris.texas.gov/>

**Comment by jseppi** [comment]
@KCMack - Made a new issue for this: #606

**Pull request merged**
