### PR TITLE
Ortho update jul 17

### PR DESCRIPTION
**Pull request by gmullins**
Weekly report and maps emailed to Chris.

### CODE REVIEW

**Comment by jseppi** [comment]
I think @christoball is out all week. Would you like me to add the images and report and deploy this update, @gmullins?

**Comment by gmullins** [comment]
Yes. I'll email them to you @jseppi since it looks like I can't attach a PDF here. Thanks!!

**Comment by KCMack** [comment]
Chris mentioned that he will return tomorrow.

Kathleen C. Mack, PMP
Operations Manager
Texas Natural Resources Information System / 1700 N. Congress Ave., Austin, Texas 78701
Phone 512 463-4536 / Cell 512 415-3847
Kathleen.Mack@twdb.texas.gov<mailto:Kathleen.Mack@twdb.texas.gov> / www.tnris.texas.gov<http://www.tnris.texas.gov/>

**Comment by jseppi** [comment]
Oh whoops. I got confused looking at all the long events in my Outlook calendar and mixed his bar up with someone else's! Almost finished anyways.

**Comment by jseppi** [comment]
Changes deployed!

**Comment by gmullins** [comment]
Looks great! @jseppi

**Pull request merged**
