### PR TITLE
Data cat org update

### PR DESCRIPTION
**Pull request by christoball**

### CODE REVIEW

**Comment by christoball** [comment]
@mitchellryant can you review for accuracy?

Article preview link is here:
https://deploy.tnris.org/api/v1/preview/6e758613433691db9141029f9628b9c3382c395c/news/2015-11-22/glo-tceq-tpwd-datasets-expand-data-catalog/

**Comment by mitchellryant** [comment]
looks good to me

**Comment by christoball** [comment]
Is 53 new datasets accurate? I got that by subtracting 167 (the number before adding) from 220, and subtracting 1 more for the HPIDS University lands.

**Comment by mitchellryant** [comment]
yes 53 is correct

**Pull request merged**
