### PR TITLE
2017 brazos ortho release

### PR DESCRIPTION
**Pull request by gmullins**
- [x] First Draft @gmullins
- [x] Add images, formatting edits @christoball
- [ ] Review built dev version
- [ ] Merge Pull Request and Publish @christoball

### CODE REVIEW

**Comment by christoball** [comment]
@gmullins  Dev page ready for review:
https://beta.tnris.org/news/2017-05-08/new-brazos-2017-aerial-imagery-now-available/

**Comment by mitchellryant** [comment]
- before the world explodes. 
- before the fourth rider breaks the seal. 
- before the seventh sign. 

the adding of English ordinal suffix for the day of the month, 2 characters. is controlled by the template used to create the page. in this case news.html. removal of the **S** from the function below should end this crime on the site. it is in several .html templates. 

`<time>{{date|date('F jS, Y')}}</time>`

**Comment by pwblanton** [comment]
You must have received an A+ in creative writing!! Love this!!!



Sent via the Samsung Galaxy S7, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by christoball** [comment]
Does @pwblanton's go ahead mean this is ready?

**Comment by pwblanton** [comment]
Waiting for @KCMack to review.

**Pull request merged**
