### PR TITLE
2017-02-28_2014-2016_FEMA-lidar-release.md

### PR DESCRIPTION
**Pull request by ThorTheDestroyer**
Please also update the data catalog where these data entries are in the staged tab.

### CODE REVIEW

**Comment by ThorTheDestroyer** [comment]
@christoball @mitchellryant 

Any reason why this still hasn't been pulled?  Anything pending that still need to be done?

**Comment by mitchellryant** [comment]
@ThorTheDestroyer 
I do not see the images for article under M:\Website\Updates
I only see 2 of 3 dir for the data catalog images under M:\Website\datacatalog\images
I do not see the supplemental reports under M:\Website\datacatalog\SupplementalReports
I do not see the breaklines under M:\Website\datacatalog\lidar-breaklines
When I check the new coming data issues #1166 #1165 #1164 I see most only have 3 or 4 steps completed. Release article\news story is second to last.

**Comment by ThorTheDestroyer** [comment]
I'll be sure to complete all the new steps and responsibilities that have been established since i submitted the pull request  20 days ago.

**Comment by mitchellryant** [comment]
the step are not new and have not changed, only the website dir moved up one level.

**Data Publication**

1. Project Manager to fill out google sheet for data catalog.
The following fields from the google sheet are utilized by the Data Catalog search functionality. Be sure any keywords which should flag the data and result from searching are found within these fields.
name
short_description
description
source
coverage_extent
date_created
tags
spatial_reference
category
agency
date_added

- Project Manager creates data catalog images
Save images here M:\Admin\Website\DataCatalogImages\tnris. 
Use M:\Admin\Website\DataCatalogImages\datacatalogimage.mxd as template.
- Project  Manager to place zipped tile index here, M:\Admin\Website\TileIndex
- Project  Manager to place zipped supplemental reports here, M:\Admin\Website\SupplementalReports

**Comment by ThorTheDestroyer** [comment]
All project manager tasks have been completed.

**Comment by ThorTheDestroyer** [comment]
Dewitt catalog images can be found in the misnamed folder: **feam_2016_dewitt** of the datacatalog\images directory.

**Pull request merged**
