### PR TITLE
Star forum talks

### LINKED ISSUE #563: Forum Agenda - Ability to 'Star' talks
Suggested by @christoball - He'll do the markup and I'll implement with JS using localStorage to save user's starred talks.

### PR DESCRIPTION
**Pull request by jseppi**
Ok, I set it up so that if any talks are starred, the unstarred talks will be in `$middarkgrey`. If no talks are starred, then all talks show up in the default text color.

I got rid of the checkbox to hide/show unstarred talks and just left the note about personalizing your agenda.

Check it out: https://deploy.tnris.org/api/v1/preview/dcb4cedb7bdf6456122e757f21116cc6812b76d3/2015-gis-forum/

Closes #563

### CODE REVIEW

**Comment by jseppi** [comment]
@christoball - Checkbox to toggle showing of starred talks has been re-implemented. I made it so that the checkbox is disabled when no items have been starred.

Couple other notes:
- **State Initiatives (Cool Enough for Government Work)** section is missing individual times
- I think the grey might be a little too similar to the background grey. I think the text should be slightly darker.

image

**Comment by christoball** [comment]
Thanks I'll make those fixes.

Is there a way to keep the checkbox state the same if you refresh or switch between pages?

**Comment by jseppi** [comment]
Good idea, I'll add checkbox persistence.

**Comment by jseppi** [comment]
@christoball - ok checkbox state persists across reloads now. Let me know if you come across any funky behavior.

**Comment by jseppi** [comment]
:+1:

**Pull request merged**
