### PR TITLE
Updating GIO meeting on Events page

### LINKED ISSUE #19: Update GIO meeting on Events Page
@christoball Please remove the July meeting and replace it with the October meeting shown on the GIO page.

### PR DESCRIPTION
**Pull request by christoball**
closes #19

### CODE REVIEW

**Comment by jwhaney** [comment]
i see you worked on the education main page in this PR. It's a small thing but the "REGISTRATION CURRENTLY CLOSED" button exceeds the parent column width at 992px > 1200px. the anchor tag there needs a max-width: 100%; i think.

image

I would recommend adding that css, but you also might want to remove the "CURRENTLY" text in that button. not needed and adds a lot of width in my opinion. I would vote to keep it simple and just say "REGISTRATION CLOSED".

**Comment by jwhaney** [comment]
i realize my comment is kinda unrelated to your PR and issue that you worked on here. if you want i can approve and merge this PR and I can create another issue for the above comment...? let me know what you think @christoball.

**Review by jwhaney — CHANGES_REQUESTED** [review]
see change suggestion in comments

**Comment by christoball** [comment]
@jwhaney I've pushed a fix. I think 'Registration currently closed' was too many words anyway so shortened it. It isn't too wide now.

**Review by jwhaney — APPROVED** [review]
cool, looks good

**Pull request merged**
