### PR TITLE
Ortho 2015 year in review

### PR DESCRIPTION
**Pull request by christoball**

### CODE REVIEW

**Comment by christoball** [comment]
Please review for final typos and edits to ready for publishing.

Article preview here:
https://deploy.tnris.org/api/v1/preview/2db7176268fd6014b6627c63d48d9b708747383c/news/2015-12-07/year-in-review-2015-statewide-orthoimagery-project/

**Comment by gmullins** [comment]
@christoball I love it! When I click on the contact project manager link at the bottom of the article, it doesn't take me far enough down to see the contact form on the project page. This is in Chrome.

**Comment by gmullins** [comment]
Also, my minor-edits commit didn't seem to make it in. 
I love the new banner image!!

**Comment by jseppi** [comment]
Nice looking page! :+1:

**Pull request merged**
