### PR TITLE
Lidar project 2016

### PR DESCRIPTION
**Pull request by christoball**

### CODE REVIEW

**Comment by christoball** [comment]
@ThorTheDestroyer @gmullins Can y'all give a final look before I push it out?
https://beta.tnris.org/2016-lidar-acquisition-project/

@rwade2126 could you also give it a once-over and let us know if you see anything that might need to change? Planning to publish as soon as everyone gives it the thumbs up.

**Comment by wilsaj** [comment]
Hold off on publishing - the intro text could has some grammar issues and copy/paste errors

**Comment by wilsaj** [comment]
working on these right now, should be ready in a few minutes

**Comment by wilsaj** [comment]
ok, I'm done

**Comment by geochik** [comment]
I think the edits and the page look fantastic!

@ThorTheDestroyer - Is Williamson Co. (and SARA for that matter) aware of our plan to push this project page out with their name on it? I only ask due to the political nature of their involvement with CAPCOG.....

**Comment by ThorTheDestroyer** [comment]
No way! It's game of thrones up in here! Lol yes the both gave me permission and approved the descriptions.
________________________________

**Comment by geochik** [comment]
Great! Next question, are the green and orange "status" bars supposed to represent the different AOIs in the map that are currently colored green and blue?

**Comment by ThorTheDestroyer** [comment]
No that is the status of the projects (haven't looked at that yet myself) . The blue and green are the different AOIS and are explained by the legend on the map. I was thinking that was going to change to different colors to but I have to get the password to cartodb.
________________________________

**Comment by ThorTheDestroyer** [comment]
In mobile you have to click on the tab to see the legend so that needs to change.
________________________________

**Comment by wilsaj** [comment]
There isn't an easy way to change the way the legend works in mobile, so I think we're just stuck with that.

I changed the colors around a bit:
 - inverted the blue and orange to put the focus on the proposed areas instead of existing, and changed the other maps to match
 - switched the TWDB proposed areas to red and yellow so they're distinct but still sort of orange

Thoughts?

**Comment by ThorTheDestroyer** [comment]
That is really what i meant. [&#X1f60a]  Thanks looks good to me!




________________________________

**Pull request merged**
