### PR TITLE
StratMap Contract Page Updates/Enhancements

### LINKED ISSUE #263: StratMap Contracts page enhancement/content changes
Plans to change content and maybe make some enhancements to the StratMap contracts page. More information and details to follow.

https://tnris.org/stratmap/stratmap-contracts/

### PR DESCRIPTION
**Pull request by Ldsmiths**
Refer to issue #263 

StratMaps Contract page updates

-updated text content
-made "vendor" cards smaller and fit full page width
-removed "vendor home" URL (now accessible only via logo)
-updated contract/DIR contract URLs based on current active contracts
-moved "FAQs" below "vendors" and made collapsible
-updated banner image to include word cloud

### CODE REVIEW

**Comment by jwhaney** [comment]
@Ldsmiths i've put in some font awesome icons on each vendor card for which categories they offer - products, services, software. these icons depend on what tags are entered in the array for each vendor object. you may want to look at changing the specific icons i chose, i just kinda guessed on what might look ok. might also want to look at the css/style i added and reconfigure/remove it from inline to the css/sass files, up to you. the tags added to each vendor object should allow us to implement some type of filtering mechanism too if you want to look at that, but i haven't gotten that far yet. lets keep trying to improve this a little. good job so far though.

an fyi, even though i'm on vacation next week, i may spend a little time looking at this. i'll reach out to you via discord if so.

**Comment by Ldsmiths** [comment]
@jwhaney I think the icons look good. I changed the "services" icon to a wrench and added a legend. I'll keep looking into the filtering.

**Comment by jwhaney** [comment]
@Ldsmiths i was reviewing this PR this morning, and i noticed that the responsiveness is a little off when you squish in the screen width less than 992px or so. When the vendor cards stack, the text list items conflict with some of the vendor logos above the text. I'd suggest maybe adding a margin-top or some padding to separate the text list items div/element from the vendor logo element above. can you please take a look at that and resolve? see below:

Screen Shot 2020-10-21 at 8 10 46 AM

also, in the interest of time, we are gonna hold off on the filtering mechanism for now. maybe we'll do a future enhancement and add that later. i like the legend you added! nice job. after we fix this little responsiveness issue, i'd say we can merge the PR to develop and send out the develop url to FR and GM to review. let me know if you have any questions or concerns.

**Comment by jwhaney** [comment]
One last thing I just thought about @Ldsmiths, what do you think about putting the legend on the top under the title section for the vendors? That way they have the information before they start scrolling down to look at the vendor section. Just a thought.

**Comment by Ldsmiths** [comment]
@jwhaney I added some margins that should fix the responsiveness issue. I also shortened "Vendor Contract Page in Progress" to "Contract Page in Progress" which also helps a little with keeping the box content more consistent on resizing. 

I agree having the legend higher up is probably good, especially if we get up to 40 vendors eventually.

**Review by jwhaney — APPROVED** [review]
i think it looks good for first version to send to develop preview url. nice work @Ldsmiths

**Pull request merged**
