### PR TITLE
platinum edit, adding geocortex

### PR DESCRIPTION
**Pull request by christoball**

### CODE REVIEW

**Comment by christoball** [comment]
@rwade2126 @pwblanton preview here:
https://deploy.tnris.org/api/v1/preview/8312073212bd3924d2bc2587d8254eb2591a1aa4/

**Comment by pwblanton** [comment]
I met with Chris and he made the suggested changes.

**Comment by christoball** [comment]
@pwblanton @rwade2126 2nd edits.

https://deploy.tnris.org/api/v1/preview/c0fcad659e9d97454b9ef38e35c9a22e227a1f12/

**Comment by KCMack** [comment]
Looks good.
Thank you.

**Pull request merged**
