### PR TITLE
Feature/ed registration buttons

### LINKED ISSUE #200: education training register button text based on api registration status
implement 3 options to show user on the registration buttons for training courses. this will hopefully prevent some confusion among users when they see a future course listed on the website but it says 'Closed' because registration was closed for one reason or another.

1. active and open for registration = green 'Register Here'
2. active but not open for registration = deactivated/greyed out 'Register Here' or maybe 'Pending'
   - date used to make sure this course is in the future. otherwise, if it is in the past then it will switch to red 'Closed' button
3. inactive and closed for registration = red 'Closed' button

### PR DESCRIPTION
**Pull request by jwhaney**
closes #200 

so i've got the logic there to determine what button is set based on both registration_open status and comparing the dates to figure out if the course is in the past or future. it ain't very pretty but its simple and seems to work ok. 

there are three button options ----> green 'Register' enabled button means its in the future and the registration is open, grey 'Register' disabled button means registration is set to closed but the course is in the future, and red 'Closed' disabled button is if registration is set to closed and the course is in the past.

i'd like for ya'll to give some input here and let me know what you think. here are a couple questions i've asked myself:
- will this cover all circumstances?
- if a course is closed but the date is still in the future, is having a greyed out button ok?
- is this worth implementing or should we do it a different way?

let me know if yall can think of anything else. thanks.

### CODE REVIEW

**Comment by jwhaney** [comment]
also, should this go to the develop branch first? i just realized i did a PR to master. idk, just a thought. not sure if this should go straight to production.

**Comment by JasonKleinert** [comment]
This implementation looks good to me based on the current way this education page is being managed. To answer your questions:

1. I'm not sure if this covers all situations because I don't know what those are. We may need to get some clarity on how this works. We have a meeting next week to discuss this stuff so maybe we can learn more then.
1. Graying out the button doesn't make it seem the class is cancelled, so that's good.
1. This is a good way to improve this page right now, but I think this registration process needs an overhaul though. The whole thing is a bit confusing.

I will wait to approve this PR until you let me know if you want to go ahead with it. I think what's here now is great to go to the site until we rework this page, which we are meeting about on Monday anyway. Happy to approve though, this code looks good.

**Comment by JasonKleinert** [comment]
I missed your second comment. It can go to master, but I'm not sure where dev and master are in relation to each other right now. It looks like you brought them up to date before this work, so if you don't think this will introduce any weirdness into master from dev let's just merge it to master.

**Comment by jwhaney** [comment]
ya, those are good points @JasonKleinert. i think we can wait on merging this and see how next weeks meeting goes.

i believe i got develop up-to-date with master but not sure which one i actually started my feature branch from. shouldn't matter though because i think master and develop were even.

**Comment by adambreznicky** [comment]
- will this cover all circumstances?

i think so... only sitch i can see outside of this, may be if a class is in the future but it's "full" (all open seats have been signed up for), which is essentially Closed but it's also not Pending like when registration is simply not setup/available yet. what you put together is definitely great. we'll just have to have a meeting/chat/discussion about if it's clear to the user if the circumstance is that they should come back to register in the future when it's available or if they shouldn't bother coming back because it's full and won't ever be available.

- if a course is closed but the date is still in the future, is having a greyed out button ok?

i think so. it looks good as a standard disabled styling.

- is this worth implementing or should we do it a different way?

i think it's definitely a step in the right direction and worth implementing.

**Comment by adambreznicky** [comment]
going straight to master is cool with me.

**Comment by jwhaney** [comment]
@JasonKleinert & @adambreznicky 
ok i've re-factored the logic to determine the registration button status. i think it's a bit cleaner and better now. i've also added the new form field prop for the registration link, removed the webpack config variable, used the old registration button js file and renamed it to determine if the tnris discount code should show up or not, based on if there are any records public at the api endpoint for training courses. 

take a look and let me know if this looks good. i tested it quite a bit on my end and the re-factor for the date logic was due to a an eventual bug we would have encountered i think. 

also should we PR this to beta or a preview branch to continue testing? or should we just push this to prod? idk.

**Comment by JasonKleinert** [comment]
were you turning some of these classes back to public to test?

**Review by JasonKleinert — APPROVED** [review]
Looks good

**Comment by JasonKleinert** [comment]
I say we go ahead and merge this into master

**Pull request merged**
