### PR TITLE
ortho-update-dec-11

### PR DESCRIPTION
**Pull request by gmullins**
Weekly update to ortho project page. Maps and report emailed to @christoball

### CODE REVIEW

**Comment by christoball** [comment]
Just wanted to clarify something here:
`TNRIS launched the 2015 0.5-meter WMS [link](https://tnris.org/maps-and-data/online-mapping-services/#texas-orthoimagery-program):`

Are you saying you want the word '**link**' to go to that part on the WMS page? @gmullins

**Comment by gmullins** [comment]
Perhaps it should be 
TNRIS launched the [2015 0.5-meter orthoimagery Web Mapping Service (WMS)](https://tnris.org/maps-and-data/online-mapping-services/#texas-orthoimagery-program)

Too long?

**Comment by christoball** [comment]
I feel like since it's going to be on the page under data access, we should just point to that:

- TNRIS launches the web mapping service for the 2015 TOP. Access the url below under **Full Statewide Dataset Access**.

**Comment by gmullins** [comment]
Perfect. Would be redundant the other way. I'd still like to put the acronym in though.

TNRIS launches the web mapping service (WMS) for the 2015 TOP. Access the url below under Full Statewide Dataset Access.

**Pull request merged**
