### PR TITLE
updated mapserver url getter to use lore populated urls vs present s3 mapfiles

### PR DESCRIPTION
**Pull request by adambreznicky**

### CODE REVIEW

**Comment by christoball** [comment]
@adambreznicky just checking on this since my review was requested. this built for me all good, the code itself is beyond my scope otherwise I would go ahead and merge.

**Comment by adambreznicky** [comment]
@christoball i merged into develop. when you're ready, go ahead and merge develop into master to deploy these changes into prod.

**Comment by christoball** [comment]
@adambreznicky didnt this pull request just merge the branch into master?

**Comment by adambreznicky** [comment]
@christoball yes, my bad. no merge necessary by you

**Pull request merged**
