### PR TITLE
Forum job board

### LINKED ISSUE #594: Forum Job Board Contact Form
Create a contact form that allows organizations to upload pdfs/docs of job openings.

Email directs to Erik O'brian and Kathleen Mack

@jseppi to help with file upload functionality

### PR DESCRIPTION
**Pull request by christoball**
closes #594

### CODE REVIEW

**Comment by jseppi** [comment]
still needs some work on our end

- the job-board page needs to be served over https only
- submission to the contact backend is not working

**Comment by jseppi** [comment]
nginx redirect has been implemented and deployed.

@wilsaj - I had forgotten a contact-app config for the new form. It's now been committed. Please redeploy contact-app.

**Comment by jseppi** [comment]
I went ahead and did the contact-app redeploy. Job Board form now works. I believe @mitchellryant will have to setup some filtering and auto-assignments in the ticketing system.

**Comment by mitchellryant** [comment]
auto assignment has been created

**Pull request merged**
