### PR TITLE
updating package.json to address dependencies

### LINKED ISSUE #192: update package dependencies
the package dependencies are out of date and 3 are showing the deprecated versions being security risks (as described in the banner on the repo). please update all package dependencies for the site. thanks!

### PR DESCRIPTION
**Pull request by christoball**
updated all out of date packages except bootstrap

closes #192

### CODE REVIEW

**Comment by jwhaney** [comment]
hey @christoball , thanks for getting to this so fast but i think you need to do some testing related to all the packages you updated. i found one issue specifically on the education page:

http://haish.tnris.org/education/

the details button is not expanding the education records coming from the api (click a 'Expand Details' button for any of the records and it doesn't expand).

there are probably many of things that need to be tested as well before we merge this.

updates take some time because you never know if the newer version still plays well with the other packages, etc. it might seem simple to update, but it can be a real worm hole. the best approach is to go update by update and test each one individually. dont bulk update all the packages, or it is difficult to find the source of a problem.

**Comment by christoball** [comment]
@jwhaney thanks, i did think that the new jquery might not jive, and I was just able to verify that's what caused that. I will update jquery when I update bootstrap.

Im looking at other stuff and think some of these packages can be discarded all together:
- clipboard: This was for the when we used to copy WMS urls. I cant find where its on the site anymore or if its in use.
- holderjs: This was for blank images. Also dont see it in use anywhere and dont really see a need for it.

The rest of the updates are for non UI stuff, and I don't believe will break anything. 

bootstrap               ^3.4.1  →   ^4.4.1 
~~clipboard               ^2.0.4  →   ^2.0.6~~ 
~~holderjs                ^2.9.6  →   ^2.9.7~~ 
jquery                  ^3.4.1  →   ^3.5.0 [not updating]
 terser-webpack-plugin   ^2.3.4  →   ^2.3.5 
 css-loader              ^3.4.2  →   ^3.5.2 
 file-loader             ^5.0.2  →   ^6.0.0 
 js-beautify            ^1.10.3  →  ^1.11.0 
 jsdom                  ^16.1.0  →  ^16.2.2 
 marked                  ^0.8.0  →   ^0.8.2 
 style-loader            ^1.1.3  →   ^1.1.4 
 webpack                ^4.41.5  →  ^4.42.1 
 webpack-cli            ^3.3.10  →  ^3.3.11

**Comment by jwhaney** [comment]
@christoball thanks for the response and thanks for looking into this further. however, i think the issue that was created by adam was meant to focus on the github identified security vulnerabilities you are able to see at the banner at the top of the repo. it shows this:

image

these are actually sub-dependencies or dependencies of dependencies (i know this because they show that they are in the package-lock.json file not the package.json), so you should identify which packages in the package.json file require these sub-dependencies and only update that package to address this issue. but be sure and test thoroughly.

you can always update other packages while you are in there updating and testing, don't get me wrong. but i'm just pointing out what spawned this specific GH issue.

let me know if you have questions.

**Comment by jwhaney** [comment]
to move forward here, i would keep this PR open, but continue to test locally on your end and look into addressing the sub-dependencies that are the source of the security vulnerability. if you look into the package-lock.json for the packages listed in the GH notification, they should say which package they support, which is the one (or more?) that should be focused on updating and then testing to make sure everything is good.

**Comment by christoball** [comment]
the last commit updated all the packages except bootstrap and jquery. The bug with the collapsible menus is no longer an issue.

It looks like though that other packages with those dependencies have not been updated. Gulp especially has some of the old ones like minimist

**Comment by adambreznicky** [comment]
based on pull request #199 , this PR conflicts quite deeply with the fixes now deployed in prod. this PR also removes the Clipboard package which is utilized by the /mapserver page (list of mapserver wms services) which would fundamentally break the 1,000+ copy buttons on that page. on a side point, click-to-copy functionality is pretty useful and it's not a bad idea to support it in case we have other reasons to implement it into the future.

for these reasons, updating the packages should be started over; reattempted from scratch as to ensure reduced conflict with the fixes that now exist in prod. it will simply be easier to do the package updates starting with the proven functional updates now in prod rather than patching this package state. i'm going to close this PR opposed to merging it.

**Pull request closed without merging**
